version: "3"
services:
  web:
    build: .
    networks:
      - network
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    env_file: ../javaman.env
    ports:
     - "3000:3000"
  api:
    image: rlkamradt/javaman:latest
    ports:
     - "3001:3001"
    networks:
      - network
networks:
  network:
